version: '3.8'

volumes:
  nexus-data:
    name: nexus-data

services:
  nexus:
    image: sonatype/nexus3:3.26.1
    container_name: nexus3
    ports:
      - 8081:8081
      - 8082:8082
      - 8083:8083
    volumes:
      - nexus-data:/nexus-data