version: '3.8'

volumes:
  nexus-data:
    name: nexus-data
  jenkins-data:
    name: jenkins-data
  postgres-data:
    name: postgres-data

services:
  nexus:
    image: sonatype/nexus3:3.27.0
    container_name: nexus3
    restart: always
    hostname: 'nexus3.marcio.com'
    ports:
      - '8081:8081'
      - '8082:8082'
      - '8083:8083'
    volumes:
      - 'nexus-data:/nexus-data'

  jenkins:
    image: jenkins/jenkins:2.235.5-lts-centos7
    container_name: jenkins
    restart: always
    hostname: 'jenkins.marcio.com'
    ports:
      - '8100:8080'
      - '50000:50000'
    volumes:
      - 'jenkins-data:/var/jenkins_home'
  
  postgres:
    image: postgres:13-alpine
    container_name: postgres
    restart: always
    hostname: 'postgres.marcio.com'
    environment:
      POSTGRES_PASSWORD: admin2020
    ports:
      - '5432:5432'
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'

  pgadmin:
    image: dpage/pgadmin4:4.25
    container_name: pgadmin
    restart: always
    hostname: 'pgadmin.marcio.com'
    environment:
      PGADMIN_DEFAULT_PASSWORD: admin2020
      PGADMIN_DEFAULT_EMAIL: marciocadev@gmail.com
    ports:
      - '15432:80'
